# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'CocoapodsMDExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # swift-markdown的CocoaPods包装（需要先指定）
  pod 'apple-swift-markdown', :git => 'https://github.com/pleisto/swift-markdown-cocoapods.git', :branch => 'main'

  # 本地pod
  pod 'MarkdownDisplayKit', :path => '../MarkdownDisplayView/'

end
